---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ACR_IMAGE_PATH_FRONTEND: ${{ secrets.ACR_LOGIN_SERVER }}/frontendmodule:1.0.${{ github.run_number }}-amd64
  ACR_IMAGE_PATH_BACKEND: ${{ secrets.ACR_LOGIN_SERVER }}/backendmodule:1.0.${{ github.run_number }}-amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install dependencies
        run: |
          make install

      - name: Login to ACR
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}

      - name: Build backend docker image
        run: |
          cd ./EdgeSolution/modules/BackendModule
          docker build -t ${{env.ACR_IMAGE_PATH_BACKEND}} -f Dockerfile.amd64 .

      - name: Build frontend docker image
        run: |
          cd ./EdgeSolution/modules/FrontendModule
          docker build -t ${{env.ACR_IMAGE_PATH_FRONTEND}} -f Dockerfile.amd64 .

      - name: Push backend docker image
        run: |
          docker push ${{env.ACR_IMAGE_PATH_BACKEND}}

      - name: Push frontend docker image
        run: |
          docker push ${{env.ACR_IMAGE_PATH_FRONTEND}}
